// The UI's side of the pipe: spawn the Bare worklet (the whole P2P backend on
// a thread inside this app), then speak the RPC protocol over its IPC. This
// is the mobile analogue of the web client's fetch('/api/…') + websocket —
// with no server socket, because the server is us.
import { Worklet } from 'react-native-bare-kit';
import * as FileSystem from 'expo-file-system';
import type { ServerEvent } from '@app/shared';
import { FrameDecoder, encodeFrame, type HelloDto } from '../../common/protocol';
// Generated by `pnpm bundle:worklet` — the packed backend (see worklet/).
import bundle from '../../worklet/app.bundle.mjs';

class BackendError extends Error {
  code: string;
  constructor(code: string, message: string) {
    super(message);
    this.code = code;
  }
}

type Pending = { resolve: (v: unknown) => void; reject: (e: Error) => void };

/** Expo inlines EXPO_PUBLIC_* at bundle time — this is a build-time switch. */
export function isSeeded(): boolean {
  return process.env.EXPO_PUBLIC_FRITH_SEEDED === '1';
}

export class Backend {
  private worklet = new Worklet();
  private decoder = new FrameDecoder();
  private pending = new Map<number, Pending>();
  private listeners = new Set<(event: ServerEvent) => void>();
  private nextId = 1;

  /** Start the worklet and open the space under the app-sandbox documents
   *  dir — mobile's data directory. There is no wider filesystem to offer:
   *  that's the platform's file-access boundary, and Frith's data model
   *  (log + sparse blobs under one dir) fits entirely inside it.
   *
   *  Seeded builds (EXPO_PUBLIC_FRITH_SEEDED=1, baked in at bundle time) use
   *  a separate throwaway dir the worklet wipes and re-seeds with the three
   *  demo spaces on every launch — `pnpm dev:seeded`, phone edition. */
  async start(): Promise<HelloDto> {
    this.worklet.start('/app.bundle', bundle);
    const { IPC } = this.worklet;
    IPC.on('data', (chunk: unknown) => this.receive(chunk as Uint8Array));
    const documents = FileSystem.documentDirectory;
    if (!documents) throw new BackendError('no-documents', 'no documents directory on this platform');
    const seeded = isSeeded();
    const dataDir = `${decodeURIComponent(documents.replace(/^file:\/\//, ''))}frith-data${seeded ? '-seeded' : ''}`;
    return this.call<HelloDto>('init', { dataDir, seeded });
  }

  private receive(chunk: Uint8Array): void {
    for (const frame of this.decoder.push(chunk)) {
      const f = frame as { id?: number; ok?: boolean; result?: unknown; error?: string; code?: string; event?: ServerEvent };
      if (f.event) {
        for (const l of this.listeners) l(f.event);
      } else if (typeof f.id === 'number') {
        const p = this.pending.get(f.id);
        if (!p) continue;
        this.pending.delete(f.id);
        if (f.ok) p.resolve(f.result);
        else p.reject(new BackendError(f.code ?? 'internal', f.error ?? 'something went wrong'));
      }
    }
  }

  call<T = unknown>(method: string, params?: unknown): Promise<T> {
    return new Promise<T>((resolve, reject) => {
      const id = this.nextId++;
      this.pending.set(id, { resolve: resolve as (v: unknown) => void, reject });
      this.worklet.IPC.write(encodeFrame({ id, method, params }));
    });
  }

  /** Subscribe to the realtime fan-out. Returns the unsubscribe. */
  onEvent(listener: (event: ServerEvent) => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  suspend(): void {
    this.worklet.suspend();
  }

  resume(): void {
    this.worklet.resume();
  }
}
